package systems.dmx.core.service;

public enum Directive {

    UPDATE_TOPIC,
    DELETE_TOPIC,

    UPDATE_ASSOCIATION,
    DELETE_ASSOCIATION,

    UPDATE_TOPIC_TYPE,
    DELETE_TOPIC_TYPE,

    UPDATE_ASSOCIATION_TYPE,
    DELETE_ASSOCIATION_TYPE
}
